Increase minimum Ruby requirement to 3.2.2
The main reason for this update is the release of i18n 1.15.0. This
version of the gem uses a feature that is only available in Ruby 3.2.x,
however, this particular gem version still lists '>= 3.1' as Ruby
requirement.

This means that under Ruby 3.1.x bundler will try to install 1.15.0,
which, in turn, leads to a NoMethodError as soon as require for
'active_support' appears in the code. The error message is:

  NoMethodError:
    undefined method `[]' for Fiber:Class

          current = Fiber[:i18n_config] || self.config = I18n::Config.new
                        ^^^^^^^^^^^^^^

The authors of i18n have already expressed their unwillingness to yank
version 1.15.0 from rubygems.org:

  https://github.com/ruby-i18n/i18n/issues/735#issuecomment-4736487158

This means that the gem is simply unable to run with Ruby 3.1.x unless
the user explicitly specifies an older version of i18n in their Gemfile.